# Pandas Basics - Exercises (SOLUTION)

You're a chemical engineer analyzing operational data from your plant's reactor monitoring system. The data covers one week of operations across 5 reactors.

## Exercise 1: Load the reactor data

Import pandas and load the reactor data from the CSV file.

In [21]:
import pandas as pd
import numpy as np

# Load the reactor data from 'reactor_data.csv'
df = pd.read_csv('reactor_data.csv')

print("Data loaded successfully!")
print(f"Total records: {len(df)}")

Data loaded successfully!
Total records: 840

## Exercise 2: View the first records

Check the first 10 rows to see what the data looks like.

In [22]:
# Display the first 10 rows
df.head(10)

,Timestamp,Reactor_ID,Temperature_C,Pressure_bar,Flow_rate_L_min,Conversion_pct,Status
0,2024-01-01 00:00:00,R-101,83.3,3.88,162.5,83.3,operational
1,2024-01-01 00:00:00,R-102,81.3,3.74,148.2,82.1,operational
2,2024-01-01 00:00:00,R-103,84.8,3.62,146.0,79.0,operational
3,2024-01-01 00:00:00,R-104,80.1,3.57,147.0,88.7,operational
4,2024-01-01 00:00:00,R-105,83.6,3.52,143.3,77.1,operational
5,2024-01-01 01:00:00,R-101,82.8,4.11,152.3,79.6,operational
6,2024-01-01 01:00:00,R-102,81.8,4.38,148.0,84.7,maintenance
7,2024-01-01 01:00:00,R-103,89.7,4.11,144.7,76.0,operational
8,2024-01-01 01:00:00,R-104,80.6,2.95,145.6,78.1,operational
9,2024-01-01 01:00:00,R-105,85.0,3.97,141.9,75.0,operational

## Exercise 3: Understand the data structure

Get basic information about the dataset.

In [23]:
# Get the shape (rows, columns)
print("Shape:", df.shape)

# Get the column names
print("\nColumns:", df.columns.tolist())

# Get data types
print("\nData types:")
print(df.dtypes)

Shape: (840, 7)

Columns: ['Timestamp', 'Reactor_ID', 'Temperature_C', 'Pressure_bar', 'Flow_rate_L_min', 'Conversion_pct', 'Status']

Data types:
Timestamp           object
Reactor_ID          object
Temperature_C      float64
Pressure_bar       float64
Flow_rate_L_min    float64
Conversion_pct     float64
Status              object
dtype: object

## Exercise 4: Get basic statistics

Calculate summary statistics for the numerical columns.

In [24]:
# Display statistical summary
df.describe()

       Temperature_C  Pressure_bar  Flow_rate_L_min  Conversion_pct
count     816.000000    821.000000       816.000000      840.000000
mean       83.913603      3.808697       148.953799       79.054048
std         2.738380      0.361850         5.880494        3.923464
min        75.000000      2.630000       131.900000       66.800000
25%        82.200000      3.580000       144.800000       76.400000
50%        83.900000      3.820000       148.700000       79.100000
75%        85.800000      4.050000       152.800000       81.900000
max        92.300000      5.000000       170.000000       91.000000

## Exercise 5: Select specific columns

You want to focus on temperature and pressure measurements.

In [25]:
# Select Reactor_ID, Temperature_C, and Pressure_bar columns
temp_pressure = df[['Reactor_ID', 'Temperature_C', 'Pressure_bar']]

print(temp_pressure.head())

  Reactor_ID  Temperature_C  Pressure_bar
0      R-101           83.3          3.88
1      R-102           81.3          3.74
2      R-103           84.8          3.62
3      R-104           80.1          3.57
4      R-105           83.6          3.52

## Exercise 6: View the last measurements

Check the most recent readings to see current reactor status.

In [26]:
# Display the last 5 rows
df.tail(5)

,Timestamp,Reactor_ID,Temperature_C,Pressure_bar,Flow_rate_L_min,Conversion_pct,Status
835,2024-01-07 23:00:00,R-101,84.2,3.78,148.2,83.6,maintenance
836,2024-01-07 23:00:00,R-102,84.1,4.19,152.4,76.1,operational
837,2024-01-07 23:00:00,R-103,88.2,3.52,145.4,73.9,operational
838,2024-01-07 23:00:00,R-104,82.5,NaN,136.0,81.1,operational
839,2024-01-07 23:00:00,R-105,85.3,3.60,151.0,72.7,operational

## Exercise 7: Filter data for a specific reactor

Get all data for reactor R-101.

In [27]:
# Filter for R-101 only
r101_data = df[df['Reactor_ID'] == 'R-101']

print(f"R-101 has {len(r101_data)} measurements")
print(r101_data.head())

R-101 has 168 measurements
              Timestamp Reactor_ID  Temperature_C  Pressure_bar  \
0   2024-01-01 00:00:00      R-101           83.3          3.88
5   2024-01-01 01:00:00      R-101           82.8          4.11
10  2024-01-01 02:00:00      R-101           80.3          3.78
15  2024-01-01 03:00:00      R-101           86.7          3.88
20  2024-01-01 04:00:00      R-101           81.4          4.06

    Flow_rate_L_min  Conversion_pct       Status
0             162.5            83.3  operational
5             152.3            79.6  operational
10            149.6            81.9  operational
15            155.0            76.7  operational
20            151.6            80.1  operational

## Exercise 8: Find high temperature conditions

Identify when any reactor exceeded 88°C.

In [28]:
# Filter for temperature > 88
high_temp = df[df['Temperature_C'] > 88]

print(f"Found {len(high_temp)} high temperature readings")
print(high_temp[['Timestamp', 'Reactor_ID', 'Temperature_C']].head())

Found 58 high temperature readings
              Timestamp Reactor_ID  Temperature_C
7   2024-01-01 01:00:00      R-103           89.7
12  2024-01-01 02:00:00      R-103           89.0
32  2024-01-01 06:00:00      R-103           88.4
42  2024-01-01 08:00:00      R-103           90.5
87  2024-01-01 17:00:00      R-103           89.2

## Exercise 9: Find reactors under maintenance

Identify all maintenance periods.

In [29]:
# Filter for Status == 'maintenance'
maintenance = df[df['Status'] == 'maintenance']

print(f"Maintenance records: {len(maintenance)}")
print(maintenance[['Timestamp', 'Reactor_ID', 'Status']])

Maintenance records: 64
               Timestamp Reactor_ID       Status
6    2024-01-01 01:00:00      R-102  maintenance
12   2024-01-01 02:00:00      R-103  maintenance
32   2024-01-01 06:00:00      R-103  maintenance
33   2024-01-01 06:00:00      R-104  maintenance
66   2024-01-01 13:00:00      R-102  maintenance
..                   ...        ...          ...
751  2024-01-07 06:00:00      R-102  maintenance
761  2024-01-07 08:00:00      R-102  maintenance
781  2024-01-07 12:00:00      R-102  maintenance
810  2024-01-07 18:00:00      R-101  maintenance
835  2024-01-07 23:00:00      R-101  maintenance

[64 rows x 3 columns]

## Exercise 10: Find high temperature in specific reactor

Check if R-101 had any readings above 87°C.

In [30]:
# Filter for R-101 AND temperature > 87
r101_high_temp = df[(df['Reactor_ID'] == 'R-101') & (df['Temperature_C'] > 87)]

print(f"R-101 high temperature events: {len(r101_high_temp)}")
print(r101_high_temp[['Timestamp', 'Temperature_C', 'Pressure_bar']].head())

R-101 high temperature events: 8
               Timestamp  Temperature_C  Pressure_bar
195  2024-01-02 15:00:00           88.4          3.39
220  2024-01-02 20:00:00           87.3          4.07
225  2024-01-02 21:00:00           88.0          4.26
375  2024-01-04 03:00:00           87.9          4.48
415  2024-01-04 11:00:00           87.7          3.96

## Exercise 11: Find optimal operating conditions

Find records where conversion is above 80% and status is operational.

In [31]:
# Filter for Conversion_pct > 80 AND Status == 'operational'
optimal = df[(df['Conversion_pct'] > 80) & (df['Status'] == 'operational')]

print(f"Optimal operating records: {len(optimal)}")
print(f"That's {len(optimal)/len(df)*100:.1f}% of all data")

Optimal operating records: 313
That's 37.3% of all data

## Exercise 12: Calculate average conditions for R-101

Find the average temperature, pressure, and conversion for reactor R-101.

In [32]:
# Calculate average temperature for R-101
avg_temp_r101 = r101_data['Temperature_C'].mean()

# Calculate average pressure for R-101
avg_pressure_r101 = r101_data['Pressure_bar'].mean()

# Calculate average conversion for R-101
avg_conversion_r101 = r101_data['Conversion_pct'].mean()

print(f"R-101 Average Conditions:")
print(f"  Temperature: {avg_temp_r101:.2f} °C")
print(f"  Pressure: {avg_pressure_r101:.2f} bar")
print(f"  Conversion: {avg_conversion_r101:.2f} %")

R-101 Average Conditions:
  Temperature: 83.56 °C
  Pressure: 3.97 bar
  Conversion: 81.09 %

## Exercise 13: Add temperature in Kelvin

Create a new column with temperature in Kelvin.

In [33]:
# Add new column: Temperature_K = Temperature_C + 273.15
df['Temperature_K'] = df['Temperature_C'] + 273.15

print(df[['Reactor_ID', 'Temperature_C', 'Temperature_K']].head())

  Reactor_ID  Temperature_C  Temperature_K
0      R-101           83.3         356.45
1      R-102           81.3         354.45
2      R-103           84.8         357.95
3      R-104           80.1         353.25
4      R-105           83.6         356.75

## Exercise 14: Categorize conversion efficiency

Create a column that labels conversion as 'High' (>82%), 'Medium' (75-82%), or 'Low' (<75%).

In [34]:
def categorize_conversion(conversion):
    if conversion > 82:
        return 'High'
    elif conversion >= 75:
        return 'Medium'
    else:
        return 'Low'

# Apply the function to create new column
df['Efficiency'] = df['Conversion_pct'].apply(categorize_conversion)

print(df[['Reactor_ID', 'Conversion_pct', 'Efficiency']].head(10))

  Reactor_ID  Conversion_pct Efficiency
0      R-101            83.3       High
1      R-102            82.1       High
2      R-103            79.0     Medium
3      R-104            88.7       High
4      R-105            77.1     Medium
5      R-101            79.6     Medium
6      R-102            84.7       High
7      R-103            76.0     Medium
8      R-104            78.1     Medium
9      R-105            75.0     Medium

## Exercise 15: Count efficiency categories

How many readings fall into each efficiency category?

In [35]:
# Count values in Efficiency column
efficiency_counts = df['Efficiency'].value_counts()

print("Efficiency distribution:")
print(efficiency_counts)

Efficiency distribution:
Efficiency
Medium    514
High      194
Low       132
Name: count, dtype: int64

## Exercise 16: Check for missing data

Identify how many missing values are in each column.

In [36]:
# Count missing values per column
missing = df.isnull().sum()

print("Missing values:")
print(missing)

Missing values:
Timestamp           0
Reactor_ID          0
Temperature_C      24
Pressure_bar       19
Flow_rate_L_min    24
Conversion_pct      0
Status              0
Temperature_K      24
Efficiency          0
dtype: int64

## Exercise 17: Fill missing temperature values

Replace missing temperature values with the average temperature.

In [ ]:
# Calculate mean temperature
mean_temp = df['Temperature_C'].mean()

# Fill missing values in Temperature_C
df['Temperature_C'].fillna(mean_temp, inplace=True)

print(f"Filled missing temperatures with {mean_temp:.2f}°C")
print(f"Missing temperatures now: {df['Temperature_C'].isnull().sum()}")

Filled missing temperatures with 83.91°C
Missing temperatures now: 0

## Exercise 18: Sort by conversion

Find the top 10 best performing readings.

In [38]:
# Sort by Conversion_pct in descending order and get top 10
top_10 = df.sort_values('Conversion_pct', ascending=False).head(10)

print("Top 10 conversion readings:")
print(top_10[['Timestamp', 'Reactor_ID', 'Conversion_pct', 'Temperature_C', 'Pressure_bar']])

Top 10 conversion readings:
               Timestamp Reactor_ID  Conversion_pct  Temperature_C  \
611  2024-01-06 02:00:00      R-102            91.0           86.1
461  2024-01-04 20:00:00      R-102            89.2           84.9
670  2024-01-06 14:00:00      R-101            88.9           81.8
3    2024-01-01 00:00:00      R-104            88.7           80.1
750  2024-01-07 06:00:00      R-101            88.4           84.1
191  2024-01-02 14:00:00      R-102            88.1           87.6
421  2024-01-04 12:00:00      R-102            87.9           87.0
178  2024-01-02 11:00:00      R-104            87.9           80.6
71   2024-01-01 14:00:00      R-102            87.8           85.4
246  2024-01-03 01:00:00      R-102            87.8           83.0

     Pressure_bar
611          3.92
461          4.45
670          4.27
3            3.57
750          4.10
191          4.25
421          4.11
178           NaN
71           3.77
246          4.03

## Exercise 19: Group by reactor and calculate averages

Calculate average temperature, pressure, and conversion for each reactor.

In [39]:
# Group by Reactor_ID and calculate mean for only numeric columns of interest
reactor_averages = df.groupby('Reactor_ID')[['Temperature_C', 'Pressure_bar', 'Conversion_pct']].mean()

print("Average conditions by reactor:")
print(reactor_averages.round(2))

Average conditions by reactor:
            Temperature_C  Pressure_bar  Conversion_pct
Reactor_ID
R-101               83.56          3.97           81.09
R-102               84.29          3.98           81.36
R-103               86.60          3.70           76.79
R-104               80.88          3.49           80.81
R-105               84.25          3.90           75.22

## Exercise 20: Find the best reactor

Which reactor has the highest average conversion?

In [40]:
# Get average conversion by reactor
avg_conversion_by_reactor = df.groupby('Reactor_ID')['Conversion_pct'].mean()

# Find the reactor with maximum average conversion
best_reactor = avg_conversion_by_reactor.idxmax()
best_conversion = avg_conversion_by_reactor.max()

print(f"Best performing reactor: {best_reactor}")
print(f"Average conversion: {best_conversion:.2f}%")

Best performing reactor: R-102
Average conversion: 81.36%

## Exercise 21: Filter operational data only

Create a clean dataset with only operational readings for further analysis.

In [41]:
# Filter for operational status only
operational_data = df[df['Status'] == 'operational']

print(f"Total records: {len(df)}")
print(f"Operational records: {len(operational_data)}")
print(f"Data availability: {len(operational_data)/len(df)*100:.1f}%")

Total records: 840
Operational records: 776
Data availability: 92.4%

## Exercise 22: Calculate pressure range by reactor

Find the minimum and maximum pressure for each reactor.

In [42]:
# Group by reactor and calculate min and max pressure
pressure_range = df.groupby('Reactor_ID')['Pressure_bar'].agg(['min', 'max'])

# Calculate range
pressure_range['range'] = pressure_range['max'] - pressure_range['min']

print("Pressure ranges by reactor:")
print(pressure_range.round(2))

Pressure ranges by reactor:
             min   max  range
Reactor_ID
R-101       3.26  5.00   1.74
R-102       3.09  4.72   1.63
R-103       2.81  4.62   1.81
R-104       2.63  4.10   1.47
R-105       3.07  4.77   1.70